CREATE TABLE Towns
(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(30) NOT NULL
)

CREATE TABLE Addresses
(
	Id INT PRIMARY KEY IDENTITY,
	AddressText NVARCHAR(MAX),
	TownId INT NOT NULL
)

CREATE TABLE Departments
(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(50) NOT NULL
)

CREATE TABLE Employees
(
	Id INT PRIMARY KEY IDENTITY,
	FirstName NVARCHAR(35) NOT NULL,
	MiddleName NVARCHAR(35) NOT NULL,
	LastName NVARCHAR(35) NOT NULL,
	JobTitle NVARCHAR(35) NOT NULL,
	DepartmentId INT NOT NULL,
	HireDate DATE,
	Salary DECIMAL NOT NULL,
	AddressId INT
)

ALTER TABLE Employees
ADD FOREIGN KEY (DepartmentId) REFERENCES Departments(Id);

ALTER TABLE Employees
ADD FOREIGN KEY (Addressid) REFERENCES Addresses(Id);

