CREATE TABLE Students
(
	StudentID INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(30) NOT NULL
)

CREATE TABLE Exams
(
	ExamID INT IDENTITY PRIMARY KEY,
	Name NVARCHAR(30) NOT NULL
)

CREATE TABLE StudentsExams
(
	StudentID INT NOT NULL,
	ExamID INT NOT NULL
)

ALTER TABLE StudentsExams
	ADD PRIMARY KEY (StudentID, ExamID);

ALTER TABLE StudentsExams
	ADD FOREIGN KEY (StudentID) REFERENCES Students(StudentID);

ALTER TABLE StudentsExams
	ADD FOREIGN KEY (ExamID) REFERENCES Exams(ExamID);